# Generated by Django 2.0 on 2019-07-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190728_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_title',
            field=models.BooleanField(default=False, verbose_name='是否置顶文章'),
        ),
    ]
